<?php 
include_once("index.html");?> 
<?php 
include_once("contact.html");?> 
<?php 
include_once("portfolio.html");?> 
<?php 
include_once("style.css");?> 
<?php 
include_once("form.css");?> 
<?php 
include_once("portfolio.css");?> 